version: '3'

services:
  nginx:
    image: nginx:stable
    container_name: nginx_parcel_storage
    volumes:
      - '.:/srv'
      - './docker/nginx/conf.d:/etc/nginx/conf.d'
    ports:
      - '8080:80'
    depends_on:
      - app
  app:
    build:
      context: ./docker/php-fpm
      dockerfile: Dockerfile
    container_name: app_parcel_storage
    volumes:
      - '.:/srv'
  pgsql:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    container_name: db_parcel_storage
    environment:
      POSTGRES_DB: parcel-storage
      POSTGRES_PASSWORD: root
      POSTGRES_USER: parcel
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data:rw

volumes:
  db_data:

